name: ${project.name}
version: ${project.version}
description: ${project.description}
website: ${project.url}
author: totemo
authors: []
main: nu.nerd.nerdore.NerdOre
api-version: 1.13

permissions:
  nerdore.admin:
    description: Permission to administer the plugin.
    default: op
  nerdore.notify:
    description: Permission to receive progress notification broadcasts.
    default: op

commands:
  nerdore:
    description: Main plugin command.
    permission: nerdore.admin
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> reload§f - Reload the configuration.
      §e/<command> notify§f - Toggle notification broadcasts.
      §e/<command> debug§f - Toggle debug logging.
      §e/<command> start§f - Start processing.
      §e/<command> stop§f - Stop processing.
      §e/<command> status§f - Show the current running state, side and index.
      §e/<command> period §f[§e<num>§f] - Set or show the period in ticks.
      §e/<command> seed §f[§e<num>§f] - Set or show the ore generation seed.
      §e/<command> side §f[§e<num>§f] - Set or show the side length in blocks.
      §e/<command> index §f[§e<num>§f] - Set or show the next converted index (non-negative) in the current world.
      §e/<command> rules§f - List the rules for the player's current world.
      §e/<command> location§f - Show the player's current world and biome.
